default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: furima_admin
  password: Furima_Aws2025!
  host: furima-db-tokyo.c98qg02cqw00.ap-northeast-1.rds.amazonaws.com
  port: 5432

development:
  <<: *default
  database: furima-db-tokyo

test:
  <<: *default
  database: furima-db-tokyo_test

production:
  <<: *default
  database: furima-db-tokyo_production
